### ISSUE TITLE
Add apcu Cache adapter

### ISSUE THREAD

**Issue by jaydiablo** [diablomedia/doctrine1#49]
As of PHP 7.0 it's not possible to use the APC extension for caching user data.  The APCU extension replaces this, and has its own `apcu_` functions for storing user data in php apps.  The `apc_` equivalents are no longer available.

It's possible to install the APCU BC module that more or less routes the `apc_*` functions to their `apcu_` equivalent (https://pecl.php.net/package/apcu_bc), but it would be nice to not have to install and depend on that module if it's easy enough to provide an apcu cache adapter class within this lib.

It seems like it would be relatively easy to add a `Doctrine_Cache_Apcu` class that just uses the `apcu_` functions, but I haven't looked to see if `apcu_` has an equivalent for every `apc_` function that Doctrine uses.

**Comment by rossmotley** [comment]
@jaydiablo We have a `Doctrine_Cache_Apcu` class we're using if that would be useful?

**Comment by jaydiablo** [comment]
@rossmotley Sure! care to make a PR?

**Comment by rossmotley** [comment]
@jaydiablo I can try - I'm not too sure if the current travis environment has apc/apcu enabled, so I am not too sure about how the tests will work.

**Comment by jaydiablo** [comment]
@rossmotley I don't believe the APC adapter has any tests hitting it, as there's no coverage for that file: https://codecov.io/gh/diablomedia/doctrine1/src/master/lib/Doctrine/Cache/Apc.php

Does look like there is an APC cache test though, I could certainly try to get that running on travis.

If you also have tests written for your `Doctrine_Cache_Apcu` class, could include them in the PR (I assume they'll either be skipped or will error out), and I can try to take some time to get APCU working on travis for those.

**Comment by rossmotley** [comment]
@jaydiablo Done - I did a copy/paste of the apc test.

**Comment by jaydiablo** [comment]
Added in #50
